<?php

namespace Convo\Core\Adapters\Alexa;

use Convo\Core\Util\AbstractEnum;

final class AlexaSkillCategoriesEnum extends AbstractEnum
{
    const ALARMS_AND_CLOCKS = "ALARMS_AND_CLOCKS";
    const ASTROLOGY = "ASTROLOGY";
    const BUSINESS_AND_FINANCE = "BUSINESS_AND_FINANCE";
    const CALCULATORS = "CALCULATORS";
    const CALENDARS_AND_REMINDERS = "CALENDARS_AND_REMINDERS";
    const CHILDRENS_EDUCATION_AND_REFERENCE = "CHILDRENS_EDUCATION_AND_REFERENCE";
    const CHILDRENS_GAMES = "CHILDRENS_GAMES";
    const CHILDRENS_MUSIC_AND_AUDIO = "CHILDRENS_MUSIC_AND_AUDIO";
    const CHILDRENS_NOVELTY_AND_HUMOR = "CHILDRENS_NOVELTY_AND_HUMOR";
    const COMMUNICATION = "COMMUNICATION";
    const CONNECTED_CAR = "CONNECTED_CAR";
    const COOKING_AND_RECIPE = "COOKING_AND_RECIPE";
    const CURRENCY_GUIDES_AND_CONVERTERS = "CURRENCY_GUIDES_AND_CONVERTERS";
    const DATING = "DATING";
    const DELIVERY_AND_TAKEOUT = "DELIVERY_AND_TAKEOUT";
    const DEVICE_TRACKING = "DEVICE_TRACKING";
    const EDUCATION_AND_REFERENCE = "EDUCATION_AND_REFERENCE";
    const EVENT_FINDERS = "EVENT_FINDERS";
    const EXERCISE_AND_WORKOUT = "EXERCISE_AND_WORKOUT";
    const FASHION_AND_STYLE = "FASHION_AND_STYLE";
    const FLIGHT_FINDERS = "FLIGHT_FINDERS";
    const FRIENDS_AND_FAMILY = "FRIENDS_AND_FAMILY";
    const GAME_INFO_AND_ACCESSORY = "GAME_INFO_AND_ACCESSORY";
    const GAMES = "GAMES";
    const HEALTH_AND_FITNESS = "HEALTH_AND_FITNESS";
    const HOTEL_FINDERS = "HOTEL_FINDERS";
    const KNOWLEDGE_AND_TRIVIA = "KNOWLEDGE_AND_TRIVIA";
    const MOVIE_AND_TV_KNOWLEDGE_AND_TRIVIA = "MOVIE_AND_TV_KNOWLEDGE_AND_TRIVIA";
    const MOVIE_INFO_AND_REVIEWS = "MOVIE_INFO_AND_REVIEWS";
    const MOVIE_SHOWTIMES = "MOVIE_SHOWTIMES";
    const MUSIC_AND_AUDIO_ACCESSORIES = "MUSIC_AND_AUDIO_ACCESSORIES";
    const MUSIC_AND_AUDIO_KNOWLEDGE_AND_TRIVIA = "MUSIC_AND_AUDIO_KNOWLEDGE_AND_TRIVIA";
    const MUSIC_INFO_REVIEWS_AND_RECOGNITION_SERVICE = "MUSIC_INFO_REVIEWS_AND_RECOGNITION_SERVICE";
    const NAVIGATION_AND_TRIP_PLANNER = "NAVIGATION_AND_TRIP_PLANNER";
    const NEWS = "NEWS";
    const NOVELTY = "NOVELTY";
    const ORGANIZERS_AND_ASSISTANTS = "ORGANIZERS_AND_ASSISTANTS";
    const PETS_AND_ANIMAL = "PETS_AND_ANIMAL";
    const PODCAST = "PODCAST";
    const PUBLIC_TRANSPORTATION = "PUBLIC_TRANSPORTATION";
    const RELIGION_AND_SPIRITUALITY = "RELIGION_AND_SPIRITUALITY";
    const RESTAURANT_BOOKING_INFO_AND_REVIEW = "RESTAURANT_BOOKING_INFO_AND_REVIEW";
    const SCHOOLS = "SCHOOLS";
    const SCORE_KEEPING = "SCORE_KEEPING";
    const SELF_IMPROVEMENT = "SELF_IMPROVEMENT";
    const SHOPPING = "SHOPPING";
    const SMART_HOME = "SMART_HOME";
    const SOCIAL_NETWORKING = "SOCIAL_NETWORKING";
    const SPORTS_GAMES = "SPORTS_GAMES";
    const SPORTS_NEWS = "SPORTS_NEWS";
    const STREAMING_SERVICE = "STREAMING_SERVICE";
    const TAXI_AND_RIDESHARING = "TAXI_AND_RIDESHARING";
    const TO_DO_LISTS_AND_NOTES = "TO_DO_LISTS_AND_NOTES";
    const TRANSLATORS = "TRANSLATORS";
    const TV_GUIDES = "TV_GUIDES";
    const UNIT_CONVERTERS = "UNIT_CONVERTERS";
    const WEATHER = "WEATHER";
    const WINE_AND_BEVERAGE = "WINE_AND_BEVERAGE";
    const ZIP_CODE_LOOKUP = "ZIP_CODE_LOOKUP";

    private function __construct() {}
}